### ISSUE TITLE
There are two 5 pms

### ISSUE THREAD

**Issue by redpanda1234** [hyperschedule/hyperschedule#1]
<img width="137" alt="screen shot 2017-11-13 at 1 31 42 pm" src="https://user-images.githubusercontent.com/25603060/32750275-07cea3f8-c877-11e7-8c95-e35c5384f309.png">

**Comment by raxod502** [comment]
Lulz. Fixed in https://github.com/raxod502/hyperschedule/commit/87bc2414d30e86ccfd9528310c766f9200d1b376.
