### ISSUE TITLE
Suggestion: use RE:DOM instead of document.createElement

### ISSUE THREAD

**Issue by kwshi** [hyperschedule/hyperschedule#107]
Currently, we use hundreds of manual calls to `document.createElement`, `el.setAttribute`, `el.classList.add`, etc. to generate HTML elements and set properties.

[RE:DOM](https://redom.js.org/documentation) is an ultra-lightweight, efficient library for creating DOMs.  I think we can produce much nicer-looking code, and in fact more efficient code, using RE:DOM to create our elements instead of manual DOM calls.

As a quick demonstration, here's some existing code used to create a course checkbox:

```javascript
const selectToggle = document.createElement("input");
  selectToggle.setAttribute("type", "checkbox");
  selectToggle.classList.add("course-box-button");
  selectToggle.classList.add("course-box-toggle");
  selectToggle.classList.add("course-box-select-toggle");
  selectToggle.checked = !!course.selected;
```

and here's how it would look using RE:DOM:

```javascript
el('input', {
  type: 'checkbox',
  className: 'course-box-button course-box-toggle course-box-select-toggle',
  checked: !!course.selected
});
```

A few nice things about using RE:DOM:
- It operates on plain, native DOM types, so it's _really_ easy to try porting parts of the app to RE:DOM incrementally, and we don't have to do a massive rewrite of all the UI code.
- RE:DOM supports a declarative list renderer that allows you to pass in a list of data objects (i.e. courses), and it does the diffing and efficient updating for you (much like React, but more lightweight and compatible with vanilla JS), which is almost certainly more efficient than what we do now, which is deleting all elements inside courseResultsSearchList and re-appendChild'ing every single time a scroll event happens, etc.
- The code is much more readable.

**Comment by raxod502** [comment]
Sounds like a great idea to me. I'd also be okay with using JSX (I believe we could even enable this in the Babel configuration right now without having to change anything else), which I think is also pretty readable and easy to understand for the unfamiliar. Either option is good.

**Comment by kwshi** [comment]
Long since obsolete, as the new frontend (V2) is getting rewritten in React.
