### ISSUE TITLE
Use better CSS

### ISSUE THREAD

**Issue by kwshi** [hyperschedule/hyperschedule#108]
Currently, scanning through the source code, I've noticed snippets of code like this:

```javascript
  const listHeight = courseSearchScheduleColumn.offsetHeight
    - columnPaddingTop
    - searchScheduleToggleBar.offsetHeight
    - courseSearchBar.offsetHeight
    - placeholderHeight;
  courseSearchResultsList.style.height = "" + listHeight + "px";

  const scheduleHeight = courseSearchScheduleColumn.offsetHeight
    - columnPaddingTop
    - searchScheduleToggleBar.offsetHeight;
  scheduleColumn.style.height = "" + scheduleHeight + "px";
```

wherein we rely on dynamic viewport calculations (that have to be attached to onResize, etc.) in Javascript to do things like scale certain elements to fit the rest of a container.  Using Javascript to manage layout dimensions is generally inadvisable and obsolete--that is the job of CSS.  

Long ago, perhaps it used to be the case that CSS lacked support for cool, flexible scaling features, forcing people to use Javascript to hack around it.  Thankfully, we _now_ (for 6+ years) have CSS Flexbox, which is a much more elegant and reliable way to _actually_ manage layouts.  The above code, as far as I can tell, can (and should) be replaced with CSS Flexbox styles, something like

```css
#course-search-schedule-column {
  display: flex;
  flex-direction: column;
}

#course-search-column, #course-schedule-column {
  flex-grow: 1;
}
```

There's probably a handful of instances throughout the app where using Flexbox can both
- simplify our JS/CSS code
- make nicer, more well-aligned layouts.

**Comment by raxod502** [comment]
Yep, sounds about right. I've refrained from commenting on the hacky JS calculations because I don't actually know how to use Flexbox, but if you do, I'd be very happy to see them be replaced with Flexbox.

**Comment by kwshi** [comment]
Started using PostCSS & rewriting/re-organizing some components, so this is a WIP, but I'm closing this issue since it falls under the broad category of "continual refactoring".
