### ISSUE TITLE
Incorrect caching?

### ISSUE THREAD

**Issue by kwshi** [hyperschedule/hyperschedule#117]
The current method of caching the course list seems to sometimes "corrupt" the locally-stored course list.  When I go on to Hyperschedule and search for certain courses (e.g. math 131), I get "No results" despite Math 131 clearly being a course; performing the same search in _incognito_ shows the correct courses.  

I'm not sure how to reproduce this issue, but my suspicion is that there's something broken with the diff-merging algorithm, or that somehow the timestamp and course list have fallen out of sync, etc.?  Perhaps we can do something, e.g. checking hashes, to validate the locally-cached course list and fix it if it breaks?

**Comment by raxod502** [comment]
Yeah, keeping a hash seems like an excellent idea to me. We've had this issue for a while. I think the right solution is to put users first and just toss the corrupted data when we detect a mismatch, but then we can go in later and add some logging to figure out what is wrong.

**Comment by mia1024** [comment]
Closed as no longer relevant (we don't cache things anymore :)
