### ISSUE TITLE
Show Pre Recs Under Course Descriptions

### ISSUE THREAD

**Issue by CarsonHerness** [hyperschedule/hyperschedule#118]
When you click on a course to show the description and professors, also have a section that lists pre recs.

**Comment by CarsonHerness** [comment]
Now seeing that this already shows up for most courses. Sorry!

**Comment by raxod502** [comment]
Note that this only shows prerequisites that the professor happened to include directly in the course description. It doesn't show anything from the _actual_ prerequisites list on Portal. (Obtaining that would be considerably harder, and possibly impossible, given the API that we're working with.)
