### ISSUE TITLE
Show course descriptions

### ISSUE THREAD

**Issue by famendola1** [hyperschedule/hyperschedule#12]
When you click on a course, the side bar only shows stuff like course code, time, professor, etc. I think it would be useful to also have the description of the course show up underneath those things. I assume that the Portal API has this information.

**Comment by raxod502** [comment]
Actually, I'm not using the Portal API (unlike C-Search). The reason for this is that the Portal API frequently returns wrong data, according to Gavin. Instead, I'm using plain web scraping on the search results page. You can see exactly what data is available here:

* https://hyperschedule.herokuapp.com/api/v1/all-courses

Thus, this feature is significantly non-trivial. However, I think it would be really cool. One possibility is to have a slower job that goes through individual courses (detect which courses people add and send this information to the backend, then cache results for those?) to report this data in the API. We'd then get everything available in the detail page, including prerequisites and such.

**Comment by raxod502** [comment]
This is blocked by #35.

**Comment by raxod502** [comment]
Completed.
