### ISSUE TITLE
Seat Counts Not Updating For Classes in Schedule

### ISSUE THREAD

**Issue by Carl-Aslund** [hyperschedule/hyperschedule#122]
The API for fetching class information appears to be working fine, since the correct seat counts show up when searching for classes, but the information for how many seats are taken in a class does not appear to be updating for any classes already added to a schedule.

**Comment by kwshi** [comment]
This should be fixed by 04140dfdb1ac84989dd62d24967631e6a92be23c.  The fix implemented is temporary, but I'll close this issue for now and point to #117 to track progress on _properly_ fixing the APi update algorithm.
