### ISSUE TITLE
Syllabus Upload

### ISSUE THREAD

**Issue by ssantichaivekin** [hyperschedule/hyperschedule#127]
User story:

When a student looks at any course description, they will be able to see and download the current or previous syllabus of the course if it is in our database. The student can also choose to upload a syllabus in case there is no syllabus or to replace the current one in our database.

Implementation:

- [x] Add a UI for uploading and showing the link to syllabus in the course description box.
- [ ] Create a Firebase database to store the schedule.
- [ ] Connect the Hyperschedule to the database and require the user to authenticate before submitting the schedule.

After clicking the upload button (as shown below), the user will be prompted to select the semester and the year, and to upload the syllabus to the server. We will be using firebase, so the process of authentication will be tightly coupled with the database. Going forward, we are planning to add other things such as AE/grutoring schedule for each class to the database too.

<img width="300" alt="Screen Shot 2020-02-20 at 1 35 31 PM" src="https://user-images.githubusercontent.com/19219105/74981465-2c0fb880-53e7-11ea-8b0b-c4c99847c8f2.png"> <img width="280" alt="Screen Shot 2020-02-20 at 1 48 46 PM" src="https://user-images.githubusercontent.com/19219105/74981785-bce69400-53e7-11ea-9ac1-56428253264d.png">

This is part of CS121 Group 1 project. The team members are @ssantichaivekin, @JoaquinDoesCode, and @nat-eh.

**Comment by kwshi** [comment]
A couple comments/questions:
- How do you guard against spam, or worse, malicious uploads?  It seems like anyone would have the power to upload anything, with no guard on whether the pdf is actually the correct syllabus, or even a valid pdf file.
  - Edit: just saw #127 says authentication will be required.  Still, is there some way, other than "honor", to make sure the uploads are correct?
- How will Hyperschedule users be motivated to upload the syllabus PDFs?  The way this seems to work is by some wiki-like mechanism, where the "community" has the power to upload PDFs if they're missing and/or outdated.  But what if no one cares enough to do so?  How many users will even care?  What proportion of Wikipedia users _ever_ contribute edits to Wikipedia pages?
- It's also worth thinking about how to implement this feature in a portable manner, so as to be (somewhat) easily adaptable for use at a different school.  For instance, the current Hyperschedule API supports a `?school=` option over a common API format to support easily switching course info between different schools.
- I also have reservations about using a Firebase store for this--it feels like having to deal with multiple backends would substantially complicate the already-somewhat-complex frontend code, and as features grow, how do we decide between (1) putting it on the Hyperschedule API, (2) putting it in the Firebase store, and (3) creating yet another new database to store it?  My suggestion is to see if we can try to think about extending the existing Hyperschedule API to enable some _extensible_ plugin-like mechanism that would enable certain features like
  - syllabus upload
  - course reviews
  - other community-contributed course info

  in a scalable manner that could then also be more easily adapted to other schools.

**Comment by mia1024** [comment]
Duplicate to #144
