### ISSUE TITLE
AE/Grutoring Hours

### ISSUE THREAD

**Issue by nefrathenrici** [hyperschedule/hyperschedule#129]
User story:
When a user adds a course, they will be able to see the Grutoring and AE hours on the weekly calendar. These hours will be added by HMC students, who will be verified by email. There will also be a checkbox allowing students to toggle the hours on the calendar.

Implementation:
- [ ] Configure existing Firebase database to store grutoring/AE hours
- [ ] Add UI for students to add grutoring/AE hours to the calendar.
- [ ] Add calendar functionality to include hours on the actual website
- [ ] Add checkbox to toggle grutoring/AE hours
- [ ] Connect the Hyperschedule to the database and require the user to authenticate before adding hours.

Structure for this will be very similar to the Syllabus Upload feature because they are similar in functionality. The main difference will be in interacting with the actual calendar UI and handling course collisions.

This is part of CS121 Group 1 project. The team members are @ssantichaivekin, @JoaquinDoesCode, and @nefrathenrici

**Comment by kwshi** [comment]
See #127 for some comments I had on structuring the database, extending the API, etc.
