### ISSUE TITLE
Time/Day Search Keyword

### ISSUE THREAD

**Issue by JeremyTsaii** [hyperschedule/hyperschedule#130]
Add-on to issue #20 “Search courses by time” submitted by PythonNut.

User Story: 

As a user, I want to filter classes by time of day and day of week so that I can find classes that fit my schedule in a more convenient fashion. Often times, I am left with a slot in my schedule that needs to be filled by a class with a specific start time and on a specific day. This feature would allow me to see courses starting at a specified time/day and easily let me fill such blocks in my schedule.

Implementation:

- [x] Add time keyword
- [x] Add day keyword

The user will be able to enter in a query like “11:00 AM” and/or “Monday” and classes that satisfy the start time/day will show up in the results. We also want the user to be able to input other keywords before/after the time/day keywords to further narrow their searches. 

![time keyword](https://github.com/JeremyTsaii/Images/blob/master/time.JPG)

![day keyword](https://github.com/JeremyTsaii/Images/blob/master/day.JPG)

This is part of CS121 Group 2. Team members include @JeremyTsaii, @godpng, @rory6103.

**Comment by kwshi** [comment]
See #131 for some comments/suggestions on the query syntax.
