### ISSUE TITLE
Multiple Schedules Functionality

### ISSUE THREAD

**Issue by JeremyTsaii** [hyperschedule/hyperschedule#140]
User Story: As a user, I want to be able to draft multiple schedules and have Hyperschedule save them. This is extremely useful for choosing alternate courses for a single semester and being able to compare the different schedule options available to you. Currently, without this functionality, I find that I must manually star/unstar courses when looking at alternates and the selected course list also expands and gets cluttered. 

We plan to allow users to have 4 separate schedules which can be switched around by simply clicking on one of 4 buttons denoting the specific schedule (look at diagram below). These buttons will be visible on the course search tab. We also want the users to be able to name these 4 schedules so that customizability and organization are increased. Clicking the plus button when adding a course will then add the course to the schedules that are currently selected and not the other ones. 

When viewing the schedule tab, there will be 4 buttons to view the specific schedule on the calendar interface. 

Diagram of our intended implementation:

![Hyperschedule Issues](https://user-images.githubusercontent.com/44514622/79398022-779c9980-7f34-11ea-83c4-d6c221438039.jpg)

This is part of CS121 Group 2. Team members include @JeremyTsaii, @godpng, @rory6103.

**Comment by mia1024** [comment]
Implemented in the new version
