### ISSUE TITLE
Totally broken

### ISSUE THREAD

**Issue by nd3rdeyn** [hyperschedule/hyperschedule#168]
Hyperschedule does not successfully pull any courses from Portal anymore. Course search shows "Fetching courses from Portal..." but never finds or shows courses. As a consequence courses cannot be added and the schedule cannot be displayed. I have talked to a few other students who are facing the same problem.

**Comment by kwshi** [comment]
Shoot, you're totally right!  It should be back up now.

**Comment by kwshi** [comment]
Okay, it's back down; I know why, but I'm currently unable to fix it for a few days.  Hang on tight; I'm on it!

**Comment by acgrobman** [comment]
Is there any update on this @kwshi? I'm trying to generate the iCal for my classes but can't because I can't load a course list at all. 😢

**Comment by JarredAllen** [comment]
Hyperschedule still works for me. I think what happens is that it's having difficulty loading the course data, but it saves it into your local storage once it loads, so people for whom it has already been downloaded are fine.

As a workaround until this is fixed, you can edit the local storage (Inspect Element -> Storage in Firefox, probably similar in other browsers) and set the value under apiData to the value manually, and it would probably work. Be advised, the file is large (2 megabytes), so manipulating all of the text can be slow: https://drive.google.com/file/d/12e-J3G98adIdddCxNGAE0qvHIU2MSCW-/view?usp=sharing 

Disclaimer: I have not tried doing this myself, nor do I actually know how the front-end works, so I can't promise that it will work. But it might be worth trying if you want hyperschedule to work for you.

**Comment by kwshi** [comment]
So sorry it's taken me so long to get around to this--I've spent a bunch of time patching things up and getting it ready for the upcoming registration season; take a look and see if it's working now.  Let me know if you run into any more issues, and I'll get right on them!  @acgrobman

**Comment by kwshi** [comment]
Should be fixed now.
