### ISSUE TITLE
Make it lag less

### ISSUE THREAD

**Issue by grenmester** [hyperschedule/hyperschedule#17]

**Comment by raxod502** [comment]
In principle, #33 will help with this.

**Comment by raxod502** [comment]
However, rewriting the application in React should be seen as a last resort for fixing performance problems. There are easier solutions.

**Comment by raxod502** [comment]
This is solved by https://github.com/MuddCreates/hyperschedule/commit/d12d42b6ecf0029b45d9c8042ea80f06ec9938eb.
