### ISSUE TITLE
Course Enrollment Numbers on my Schedule Don't Update

### ISSUE THREAD

**Issue by JarredAllen** [hyperschedule/hyperschedule#176]
All of my classes show 0 students enrolled if I look at my schedule. The course list shows numbers which match those on Portal. Is there a reason for this disconnect?

**Comment by kwshi** [comment]
Yep!  The reason for the disconnect is that I did dumb things with the code.  I just went and pushed a fix to this--please take a look again and see it starts updating correctly.  Thanks!

**Comment by JarredAllen** [comment]
It works for me, so I'm going to close this issue. Thanks!
