### ISSUE TITLE
mobile friendliness?

### ISSUE THREAD

**Issue by apomyxis** [hyperschedule/hyperschedule#19]
perhaps not a high priority, but certainly would be a nice thing to have. especially given current mobile appearance...

https://drive.google.com/file/d/1ae7FHaz5Wt9X_3DTdhwZMl7FFRY5rV_2wg/view?usp=drivesdk

beautiful.

**Comment by raxod502** [comment]
This requires thought with regard to what interface people want. It's not exactly easy to show an entire schedule on screen at once on mobile.

**Comment by raxod502** [comment]
Closed in favor of #23.
