### ISSUE TITLE
Attempt to normalize credits, and allow changing credit count in UI

### ISSUE THREAD

**Issue by raxod502** [hyperschedule/hyperschedule#21]
I asked the following:

> For converting between on-campus and off-campus credits, is it always just multiplying by 3? I had thought that PE classes counted as 1 credit on-campus, but they're listed as 0.25 credits, so that would give 0.75 credits. Is there a foolproof way to calculate the credit ratio?

The registrar replied:

> No. There is much more happening behind the scenes than a scrape of the portal can capture. 
>
> The class schedule displays the units as they default at the home college of the course, not the conversion value at the home college of the student. While the 3:1 ratio is applicable in most cases, there are 1-unit courses at the other 4 undergraduate colleges that come in as 4 credits at HMC.  Some 0.25 courses come in as 0, others as 1.  I can keep going. 
>
> There is an exception process built into the course schedule construction process, which is called during the registration process, which employs the exception engine. But setting it up requires our office to manually update dozens of sections taught at the other colleges every semester. (The same occurs at each college, even those who are all on the 1-unit standard, so this isn't simply a Mudd issue.) 

I think that we should do _something_ about this, even if it is just "don't try to convert the credits".

cc @kwshi, see also #4.

**Comment by cross1** [comment]
Currently, the credit count does some weird stuff from what I've been observing. It's a bit frustrating, maybe because I'm still trying to figure out how to use the new tool alongside how I personally like to do schedules, but maybe we could do something to fix the PE credits? Also, what translates to 4 Mudd credits?

**Comment by raxod502** [comment]
Well, as you can see above, there's no general solution. What kind of change would you suggest to make it work better with your workflow?

**Comment by raxod502** [comment]
I think we should add some heuristics to fix things like PE, and then allow users to customize credit counts themselves in the UI.

**Comment by raxod502** [comment]
I did some normalization; for further work see #68.
