### ISSUE TITLE
Add support for mobile usage

### ISSUE THREAD

**Issue by irisxzhou** [hyperschedule/hyperschedule#23]
Scaling is off, so effectively on mobile hyperschedule is unusable without requesting the desktop site. Also, search is noticeably laggy and slow (I thought it crashed my browser at first). Mobile might be a less ideal way to actually register for classes, but it is still a good way to check if classes are still open.

**Comment by ssantichaivekin** [comment]
I feel like mobile support would require a whole redesign of UI/UX. For now, I purpose we only show the search input box and the course display (without the + [add course to schedule] button). That is, the mobile version is used solely for viewing available classes.

**Comment by raxod502** [comment]
Well, it would be an improvement on what we have currently, and it seems kind of dumb to maintain a copy of your schedule both on desktop and on mobile, so I don't think I object to that idea.

**Comment by Owen-Gillespie** [comment]
I strongly disagree with the assumption you make that people will have a copy of their schedule on their computer. My schedule is constantly changing as I learn about new classes and even with how bad it currently is (well was), I use hyperschedule significantly on my phone. It’s fine to decide it’s too much work, but I strongly disagree that with you assertion that making a schedule from your phone isn’t a valuable feature for many users

**Comment by ssantichaivekin** [comment]
![screen shot 2018-07-17 at 9 29 44 pm](https://user-images.githubusercontent.com/19219105/42859885-8389a80e-8a09-11e8-9dd6-cb7893d587b2.png)
![screen shot 2018-07-17 at 9 32 42 pm](https://user-images.githubusercontent.com/19219105/42859889-85319f40-8a09-11e8-9a19-2665fea46ac2.png)

How about something like this? We keep the schedule but remove course name from mobile schedule. We also move the course list below the schedule. Note that we will also need a way to display course description.

**Comment by ssantichaivekin** [comment]
Also about the laggy and slow part, was she talking about before the pagination, where we generate everything when something changes in the search box, or after?

**Comment by raxod502** [comment]
Iris' comment was from November 2017 :)

Mobile performance has no trouble at all now.

**Comment by kwshi** [comment]
Took us a while, but we finally implemented a mobile-friendly sidebar & scaling:

![hyperschedule-iphone](https://user-images.githubusercontent.com/3887189/114225867-b850a800-9927-11eb-95f7-e03d485cb550.gif)
