### ISSUE TITLE
Add way to obtain exact course code as displayed on Portal

### ISSUE THREAD

**Issue by irisxzhou** [hyperschedule/hyperschedule#24]
Through no fault of your own, Portal has really inconsistent spacing between the department name and the number of the course (e.g. CL 057 vs. ARHI184). However, you have it always displayed with the space. 

I think it looks better this way, but it makes using Hyperschedule as a reference during registration worse, because adding or removing the space in the course code will prevent you from finding the course on Portal.

**Comment by raxod502** [comment]
It would be easy to make it retain the space, or lack thereof. But, I think this is a nasty solution. What do you think would be a good UI?

**Comment by raxod502** [comment]
I think we should have the API return enough information in order to reconstruct the exact course code. It shouldn't be hard to expose this somehow in the UI.

**Comment by raxod502** [comment]
No need for this. I realized that there is a simple, obvious algorithm for generating the exact course code. Just pad the department to four characters with spaces:

```
CSCI195
MUS 088
CL  057
```

Actually, it seems that most of the restrictions on course metadata are to make the ASCII-art table on your transcript line up.
