### ISSUE TITLE
Joint Music credits counted incorrectly

### ISSUE THREAD

**Issue by slhale** [hyperschedule/hyperschedule#27]
Courses like choir and orchestra in the joint music program (which have JM instead of HM on their course code) count as 1 credit on Mudd despite being 0.5 "off campus" credits. Also they count as Mudd hums, so I don't know if they should be labeled as on or off campus.

**Comment by raxod502** [comment]
There's no general solution for this. See #21. We're considering just adding heuristics to try to approximate all of these cases.

Thanks for the report.

**Comment by slhale** [comment]
Special casing for the music might be useful because a disproportionate amount of Mudders are in choir an orchestra, but that is a design decision. Thanks for the response.
