### ISSUE TITLE
Make sure course details are always displayed

### ISSUE THREAD

**Issue by grenmester** [hyperschedule/hyperschedule#28]
It would be better to have the course box as a float on the upper right-hand corner. This is because if I were to want to look at information regarding a course which is all the way on the bottom of my list of selected courses, I would have to scroll all the way to the bottom, click the course, then scroll all the way back up to the top, which is rather inconvenient. This is especially true when you are doing it multiple times.

**Comment by ingridt123** [comment]
Could cause problems if the screen is not tall enough and the course box is longer, otherwise you won't be able to view the selected course list

**Comment by kwshi** [comment]
> Could cause problems if the screen is not tall enough and the course box is longer, otherwise you won't be able to view the selected course list

For the most part, I don't think this will be a large issue.  One workaround, however, may be to set a maximum height and scroll _within_ the course details pane after that?  

I do find it very inconvenient to have to scroll back up and down sometimes just to get a look at the course details and think it's much nicer if the course details were always visible, in the same way the search input is always visible.

**Comment by kwshi** [comment]
I'll try to resolve this together with the CSS improvements; see #108.

**Comment by ingridt123** [comment]
> > Could cause problems if the screen is not tall enough and the course box is longer, otherwise you won't be able to view the selected course list
> 
> For the most part, I don't think this will be a large issue. One workaround, however, may be to set a maximum height and scroll _within_ the course details pane after that?
> 
> I do find it very inconvenient to have to scroll back up and down sometimes just to get a look at the course details and think it's much nicer if the course details were always visible, in the same way the search input is always visible.

I think when I tried to implement this it was largely a problem on phones.

**Comment by kwshi** [comment]
Fixed.  The course details box is always visible (regardless of how you scroll the selected courses list), but if it's taking up too much vertical space, there's now a "close" button you can use to hide the course details.
