### ISSUE TITLE
CS 60 is listed as a half semester course? 

### ISSUE THREAD

**Issue by redpanda1234** [hyperschedule/hyperschedule#29]
Despite being 3 credits

**Comment by raxod502** [comment]
Amusingly enough, this is because it's a fall-semester course, and I only programmed support for spring-semester courses.

**Comment by raxod502** [comment]
Somewhat less amusingly, it appears that the entire course search now returns results from the fall semester rather than the spring semester, since the registrar changed the default term.

**Comment by raxod502** [comment]
Somebody should probably fix that.

**Comment by raxod502** [comment]
I have fixed this. See also #31.
