### ISSUE TITLE
Show whether course is open or closed in course details pane

### ISSUE THREAD

**Issue by raxod502** [hyperschedule/hyperschedule#34]
Currently, there is no way to see whether a course is open or closed without scrolling down the list of selected courses to find it. This should be changed.

**Comment by ingridt123** [comment]
Which one would people prefer?
1. "(open/closed)" after the course name
2. "(open/closed, 15/16 seats filled)" after the course name
3. "Open/Closed, 15/16 seats filled" as the last entry in the course description box

<img width="372" alt="Screen Shot 2019-08-03 at 12 17 25 PM" src="https://user-images.githubusercontent.com/19776302/62416070-48820a00-b5e9-11e9-8652-4c1425a96d26.png">
<img width="371" alt="Screen Shot 2019-08-03 at 12 17 43 PM" src="https://user-images.githubusercontent.com/19776302/62416071-48820a00-b5e9-11e9-91d8-1cea4b246bf9.png">
<img width="369" alt="Screen Shot 2019-08-03 at 12 19 39 PM" src="https://user-images.githubusercontent.com/19776302/62416072-48820a00-b5e9-11e9-9761-97e8c72c22d9.png">

**Comment by raxod502** [comment]
Looks like this issue is solved by Ingrid.
