### ISSUE TITLE
Implement total credit counters

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#37]
Currently, no credit totals for the current schedule are displayed. This is a useful feature and should be brought back.

## Plan
* [ ] Implement a component that displays course credit totals. 
* [ ] Implement a container that computes the credit totals from the store, reusing the logic from the original hyperschedule (which should be placed in `src/model.js`).
* [ ] Rejoice and be merry.

Note that this does not require any modifications to the application state management, which should make it relatively straightforward.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#1
