### ISSUE TITLE
Cleanup weekly schedule rendering

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#38]
This is a meta issue.

Currently, `components/MainPanelSchedule.js` produces incorrect or suboptimal HTML:

1. [ ] No `key` is provided for slot entities (i.e. the classes in the weekly visualizer), which is bad for performance. See [here](https://reactjs.org/docs/lists-and-keys.html) for a discussion of keys. It would be ideal to use the `courseId`s, which serve as references in the store as `key`.

2. [ ] Fix illegal markup. #40 

4. [ ] Fix incorrect rendering abstractions. #41

# Plan
In addition to fixing these issues, it is worth considering potential alternative rendering strategies for the schedule, as accurate placement of the slot entities has proven tricky, especially across browsers and screen resolutions.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#2
