### ISSUE TITLE
Implement colors for courses

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#39]
Autogenerated colors for course elements (e.g. in the course search, course list, and weekly schedule) is a nice feature and should be brought back.

## Plan
* [ ] Bring the code that computes the course colors into `src/model.js`.
* [ ] Modify components to receive a color prop.
* [ ] Modify containers to pass colors generated using the code from `src/model.js`. 

Relevant components are:
* `CourseSearchItem`
* `CourseListItem`
* `MainPanelSchedule`

(And their corresponding containers)

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#3
