### ISSUE TITLE
Hyperscheduler does not list credit count of displayed classes.

### ISSUE THREAD

**Issue by hmzh-khn** [hyperschedule/hyperschedule#4]
From the other scheduler,
![image](https://user-images.githubusercontent.com/2308491/32798187-d0c49928-c928-11e7-8c78-72ac0e79b5b2.png)

**Comment by kwshi** [comment]
Fixed in 5638292b7659a7a54f0da29db13b6f75260d5171.  Total (off-and-on-campus) credits are currently calculated as `onCampus + 3 * offCampus`.  This might change.
