### ISSUE TITLE
Fix illegal HTML in weekly schedule view

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#40]
Currently, `components/MainPanelSchedule.js` produces incorrect HTML:

1. The schedule nests a `<p>` as a direct descendant of a `<p>`, which is illegal. 
2. The schedule nests a `<div>` as a direct descendant of a `<table>`, which is illegal.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#4
