### ISSUE TITLE
Move slot entity HTML generation into its own component

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#41]
The HTML for slot entities is currently computed in `src/model.js`. This is a horrifying travesty that must be corrected.

Ideally, a slot entity would be its own self-contained component. This will pave the way for implementing actions based on their contents.

**Comment by PythonNut** [comment]
The immediate crisis has been averted, although the solution is hardly optimal.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#5
