### ISSUE TITLE
Arrange elements visually

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#43]
Currently, the app is almost entirely unstyled components with no respect for visual structure.

## Plan

1. [ ] Make the height of the `CourseSearchList` responsive and size appropriately. 
2. [ ] Put the course list to the right of the `MainPanel` and size appropriately.

Note that this will likely demand new structure in the HTML.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#7
