### ISSUE TITLE
Add Import/Export functionality

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#47]
When exporting, we can simply dump the `courseList` field from the store, either with entries substituted for full course objects ala `courses` or in a simple text format.

When importing, we will need to validate the input before committing it to the store.

**Comment by raxod502** [comment]
I'm of the opinion that, going forward, we should not make any assumptions about the well-formed-ness of the course data. That way we can handle mistaken API responses and user input. The current app does not do a great job of this.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#11
