### ISSUE TITLE
Support unselected and starred courses

### ISSUE THREAD

**Issue by PythonNut** [hyperschedule/hyperschedule#48]
Presently, all courses are selected. The ability to select and star courses is important, so it will need to be reimplemented.

# Plan

* [x] Switch `store`'s `courseList` field from a `List` to an `OrderedMap` and map from the `courseId`s to `Map`s with the selected and starred properties.
* [x] Write four new actions w/ creators `selectCourse`, `unselectCourse`, `starCourse`, `unstarCourse`.
* [x] Write the relevant reducers in `src/reducers.js`.
* [x] Modify `CourseListItem` to send these actions.
* [x] Update `VisibleMainPanelSchedule` to take these properties into account when computing the current schedule.

**Comment by raxod502** [comment]
This issue was moved to MuddCreates/hyperschedule-react#12
