### ISSUE TITLE
Removing one course from schedule removes all other courses from the schedule

### ISSUE THREAD

**Issue by ssantichaivekin** [hyperschedule/hyperschedule#58]

**Comment by raxod502** [comment]
That's really bad. Thanks for the report.

**Comment by ssantichaivekin** [comment]
The code fix was quite funny.

**Comment by raxod502** [comment]
Keep in mind that I had never done any JavaScript development before Hyperschedule.

**Comment by ssantichaivekin** [comment]
I’m not saying that you should not have missed it. I haven’t done a lot of javascript either. It’s just that it’s quite funny. 😂
