### ISSUE TITLE
Export to iCal is not working

### ISSUE THREAD

**Issue by ianrabt** [hyperschedule/hyperschedule#63]
Clicking the button "To iCal" does not result in any action (i.e. clicking this does not make an iCal file download)

**Comment by raxod502** [comment]
Confirmed. Thank you for the report.

**Comment by raxod502** [comment]
Previously, only starred courses were exported, and the export failed silently if no courses were starred.

Now, if no courses are starred, then non-starred courses are also considered. Furthermore, if no courses are added to your personal list, then an error message is displayed on attempting to export.

**Comment by ianrabt** [comment]
Thanks for the quick response!
