### ISSUE TITLE
Classes that are co-taught by Mudd profs but are listed as joint (JT) add 9 credits to the total

### ISSUE THREAD

**Issue by irisxzhou** [hyperschedule/hyperschedule#77]
The two examples I have found of this are for EA 174 and CSCI 181R, which are jointly taught by a Mudd and non-Mudd professor. Other JT classes without Mudd profs are listed using the non-Mudd credits convention (i.e. as 1 credit classes), but these are listed as 3 credits. Since it seems like non-HM classes are multiplied by 3 by default, it causes an error (and gave me quite a shock this morning).

**Comment by raxod502** [comment]
Can confirm. Can you think of a consistent way to determine the credit count multiplier such that this case is avoided?

Perhaps we can simply assume that a 3-credit class off-campus is actually 1-credit.

**Comment by irisxzhou** [comment]
Yeah, from a quick few searches, it seems like non-Mudd classes are only ever 0, 0.5, or 1 credit (0 credits are usually PE or lab).  Mudd classes go anywhere from 0 to 4. 

Not saying that I looked especially thoroughly, but I think that'd probably work.

**Comment by raxod502** [comment]
Should be fixed now.
