### ISSUE TITLE
Please add CGU courses thank you very much :)

### ISSUE THREAD

**Issue by dannykliu** [hyperschedule/hyperschedule#79]
yes pls

**Comment by raxod502** [comment]
![image](https://user-images.githubusercontent.com/6559064/56634678-b21c7080-6617-11e9-855f-59c3eb4e1c75.png)

**Comment by dannykliu** [comment]
What about all the other CGU courses listed here: https://mycampus.cgu.edu/web/mycampus/class-schedule

**Comment by raxod502** [comment]
Are they available through Portal? If not, how can the data be obtained?

**Comment by dannykliu** [comment]
They're not available through the 5C portal but are available through the link in my previous comment

**Comment by raxod502** [comment]
I don't plan on implementing this but would be happy to review pull requests :)
