### ISSUE TITLE
Same course from different college isn't mutually exclusive

### ISSUE THREAD

**Issue by AmitHarlev** [hyperschedule/hyperschedule#99]
![hyperscheduleBug](https://user-images.githubusercontent.com/8431476/63473286-cb002b80-c429-11e9-892a-546eba4064e8.PNG)

Both of these are the same course but they still both show up on the schedule. I think it's because they're from different colleges but didn't fully check this.

**Comment by raxod502** [comment]
Yes, two courses aren't considered mutually exclusive if they're from different colleges. If I recall correctly, there are some courses at different colleges that have the same course codes but are actually different courses. I'm not sure whether the situation is better or worse when we ignore this.

**Comment by mia1024** [comment]
Closing as we are no longer using mutual-exclusion key
